### PR TITLE
IP addr and data usage api

### PR DESCRIPTION
**Pull request by yosemitebandit**
PTAL -- creates an API for getting the IP addr and GPRS data usage rates for a subscriber (or for all subs)

subscribers had `ipaddr` and `port` attributes already, but those are really their `openbts_ipaddr` and `openbts_port`, so I changed those names accordingly.

### CODE REVIEW

**Comment by shaddi** [comment]
Oh snap! Exciting. Question: what happens when an IMSI shows up multiple times in the MS list, and what happens if the IMSI has multiple IPs associated with it?

**Comment by yosemitebandit** [comment]
would loooove to get the output of `gprs list` for edge cases like these so I can add it to the tests.  Currently, the parsing would still work, but it would be "last IMSI or listed IP wins"

**Comment by yosemitebandit** [comment]
I can play around with GPRS too to try and generate these odd results.

**Comment by shaddi** [comment]
I'll be doing some GPRS testing this week w/ a full-scale CCN1 so I'll see if I can generate that for you.

**Comment by yosemitebandit** [comment]
awesome, I was unable to generate any GPRS weirdness last night, but I was just testing with one phone so that's to be expected.  (On the plus side this openbts-python lib did seem to be working, it was fetching GPRS data from the live instance.)

more files like [this one](https://github.com/endaga/openbts-python/blob/subscriber-gprs-ipaddr-api/openbts/tests/fixtures/openbts_cli_gprs_list_output.txt) would be fantastic.

**Comment by shaddi** [comment]
Got it, how was that generated, `OpenBTSCLI -c "gprs list ms -v"`?

**Comment by yosemitebandit** [comment]
I'm just getting the full output: `OpenBTSCLI -c "gprs list"`

**Comment by shaddi** [comment]
Ok, got it!

**Comment by yosemitebandit** [comment]
what do you think about merging this now and then doing a PR later when we get weird `gprs list` logfiles?

**Comment by shaddi** [comment]
sgtm!

**Pull request merged**
