### PR TITLE
Put the runtime deps in setup.py

### PR DESCRIPTION
**Pull request by shaddi**
Moving runtime deps (as opposed to development deps) into setup.py.

### CODE REVIEW

**Comment by yosemitebandit** [comment]
LGTM

**Comment by shaddi** [comment]
Should this include a version bump?

**Comment by shaddi** [comment]
I think actually it doesn't unless we want to update PyPI now with the shorter deps list.

**Comment by yosemitebandit** [comment]
yah, I think it's fine without a version bump

**Pull request merged**
